// Generated by https://quicktype.io
export type projectIdType = 'APPMOVIL' | 'BACKEND' | 'WEB';

export interface PortfolioResponse {
  ok: boolean;
  projects: Project[];
}

export interface Project {
  appstore?: string;
  bannerUrl: string;
  category: projectIdType;
  docsUrl?: string;
  github?: string;
  name: string;
  playstore?: string;
  technologies: string[];
  textId?: string;
  uid: string;
  url?: string;
}
